---


- name: Wordpress | dir move wordpres
  command: 
      mv /tmp/wordpress /usr/share/nginx/html/wordpress

- name: Wordpress | Set permissions 
  file:
     path=/usr/share/nginx/html/wordpress
     owner=nginx
     group=nginx
     mode=777
     state=directory
     recurse=yes

- name: Wordpress | Copy entrypoint.sh
  copy:
     src=entrypoint.sh
     dest=/tmp/
     mode=777

- name: Wordpress | Copy install-wp.sh
  copy:
     src=install-wp.sh
     dest=/tmp/
     mode=777


- name: apk | Install curl
  apk: 
     name=curl
     state=present 

- name: apk | Remove cache
  file: 
     state=absent 
     path={{ item }}
  with_fileglob:
     - /var/cache/apk/*
